#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Perl-Tidy
Version  : 20180220
Release  : 2
URL      : https://cpan.metacpan.org/authors/id/S/SH/SHANCOCK/Perl-Tidy-20180220.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/S/SH/SHANCOCK/Perl-Tidy-20180220.tar.gz
Summary  : 'indent and reformat perl scripts'
Group    : Development/Tools
License  : GPL-2.0
Requires: perl-Perl-Tidy-bin = %{version}-%{release}
Requires: perl-Perl-Tidy-license = %{version}-%{release}
Requires: perl-Perl-Tidy-man = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
Welcome to Perltidy!
Perltidy is a tool to indent and reformat perl scripts. It can also
write scripts in html format.

%package bin
Summary: bin components for the perl-Perl-Tidy package.
Group: Binaries
Requires: perl-Perl-Tidy-license = %{version}-%{release}
Requires: perl-Perl-Tidy-man = %{version}-%{release}

%description bin
bin components for the perl-Perl-Tidy package.


%package dev
Summary: dev components for the perl-Perl-Tidy package.
Group: Development
Requires: perl-Perl-Tidy-bin = %{version}-%{release}
Provides: perl-Perl-Tidy-devel = %{version}-%{release}

%description dev
dev components for the perl-Perl-Tidy package.


%package license
Summary: license components for the perl-Perl-Tidy package.
Group: Default

%description license
license components for the perl-Perl-Tidy package.


%package man
Summary: man components for the perl-Perl-Tidy package.
Group: Default

%description man
man components for the perl-Perl-Tidy package.


%prep
%setup -q -n Perl-Tidy-20180220

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Perl-Tidy
cp COPYING %{buildroot}/usr/share/package-licenses/perl-Perl-Tidy/COPYING
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.26.1/Perl/Tidy.pm
/usr/lib/perl5/vendor_perl/5.26.1/Perl/Tidy.pod

%files bin
%defattr(-,root,root,-)
/usr/bin/perltidy

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Perl::Tidy.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Perl-Tidy/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/perltidy.1
